[general]
live_config_reload = true
# ipc_socket = true # required for alacritty msg config $options

import = [
"/home/dc/.config/alacritty-theme/themes/monokai_charcoal.toml",
"./font.default.toml",
"./window.default.toml",
"./input.default.toml"]

# note: relative paths are relative to the file _after_ links resolved
# "../alacritty-theme/themes/github_dark_colorblind.toml",
# "/home/dc/.config/alacritty-theme/themes/blood_moon.toml",
# "/home/dc/.config/alacritty-theme/themes/hyper.toml",

[terminal]
# shell = "/bin/bash"

#[terminal.shell]
#program = "/bin/bash"
# shell = "<string>" | { program = "<string>", args = ["<string>",] }

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[cursor]
style = "Block"
unfocused_hollow = true

[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3
